config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home' 
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'catalog' => 'store#index'
  get 'orders' => 'orders#index'
  get 'products' => 'products#index'
  get 'password_resets/new'
  get 'password_resets/edit'

  get 'auth/vkontakte/callback' => 'omniauth#create'
  
  resources :products
  resources :carts
  resources :line_items
  resources :orders

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with:    %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }

  def self.latest
    Product.order(:updated_at).last
  end

  private

    # убеждаемся в отсутствии товарных позиций, ссылающихся на данный товар
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include CurrentCart 
  before_action :set_cart
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:index, :new, :edit, :destroy]

  # GET /products
  # GET /products.json
  def index
    @cart = Cart.find_by!(params[:id])
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @cart = Cart.find_by!(params[:id])
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @cart = Cart.find_by!(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @cart = Cart.find_by!(params[:id])
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Товар был успешно создан.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Продукт был успешно обновлен.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Продукт успешно удален.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end

    def admin_user
      unless logged_in? && current_user.admin?
        redirect_to(root_url)
      end 
    end    
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>

        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>

        <%= f.label :image_url %>
        <%= f.text_field :image_url, class: 'form-control' %>

        <%= f.label :price %>
        <%= f.text_field :price, class: 'form-control' %>
        <br>
        <%= f.submit "Сохранить изменения", class: "btn btn-sky" %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<% provide(:title, 'Редактирование товара') %>
<h1>Редактирование товара</h1>

<%= render 'form' %>

<%= link_to 'Показать товар', @product %> |
<%= link_to 'Назад', products_path %>

app/views/products/index.html.erb
<% provide(:title, 'Товары') %>

<all_products>
    <div class = "container" style = "padding:30px;">
        <div class="panel panel-default">
              <div class="panel-heading">
                  <div class = "row" style = "padding: 0 20px 0 20px">
                    Товары
                    </div>
                </div>
            <div class="panel-body">
                <table class="table-bordered table-striped table">
                    <% @products.each do |product| %>
                      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
                        <td>
                          <%= image_tag(product.image_url, class: 'list_image img-responsive', style:"max-height:70px;") %>
                        </td>
                        <td class="list_description">
                          <dl>
                            <dt><%= product.title %></dt>
                            <dd><%= truncate(strip_tags(product.description), length: 80) %></dd>
                          </dl>
                        </td>
                        <td class="list_actions">
                          <%= link_to 'Показать', product %><br/>
                          <%= link_to 'Редактировать', edit_product_path(product) %><br/>
                          <%= link_to 'Удалить', product, method: :delete,
                                      data: { confirm: 'Вы уверены?' } %>
                        </td>
                      </tr>
                    <% end %>
                </table>
                <br>

                    <%= link_to 'Новый товар', new_product_path %>
            </div>
        </div>
    </div>
</all_products>

app/views/products/new.html.erb
<% provide(:title, 'Новый товар') %>

<new_product>
    <div class = "container" style = "padding:30px;">
        <div class="panel panel-default">
              <div class="panel-heading">
                  <div class = "row" style = "padding: 0 20px 0 20px">
                    Новый товар
                    </div>
                </div>
            <div class="panel-body">
                <%= render 'form' %>
                <br>
                <%= link_to 'Назад', products_path %>
            </div>
        </div>
    </div>
</new_product>

app/views/products/show.html.erb
<% provide(:title, 'Просмотр товара') %>
<p id="notice"><%= notice %></p>

<item>
  <br>
  <div class = "container">
    <div class = "row">
      <!--БОЛЬШОЕ ИЗОБРАЖЕНИЕ-->
      <!--БОЛЬШОЕ ИЗОБРАЖЕНИЕ-->
      <!--БОЛЬШОЕ ИЗОБРАЖЕНИЕ-->
      <div class = "col-lg-5 col-sm-5 col-xs-9 col-lg-offset-1" style = "padding-right:20px;">
          <%= image_tag(@product.image_url, class:"img-responsive center-content", style:"max-height:350px;") %>
      </div>
      <!--ИНФОРМАЦИЯ/ЗАКАЗАТЬ-->
      <!--ИНФОРМАЦИЯ/ЗАКАЗАТЬ-->
      <!--ИНФОРМАЦИЯ/ЗАКАЗАТЬ-->
      <div class="details col-md-6">
      <h3 class="product-title"><%= @product.title %></h3>
      <div class="rating">
        <div class="stars">
            <!--Хитрый цикл на звездочки (темные)-->
            <i class = "fa fa-star text-g14"></i>
            <!--Хитрый цикл на звездочки (темные)-->
            <!--Хитрый цикл на звездочки (светлые)-->
            <i class = "fa fa-star text-g14" style="color:#f2f2f2;"></i>
            <!--Хитрый цикл на звездочки (светлые)-->
        </div>
      </div>
      <p class="product-description">Классное кресло мешок для практичных натур! Прочная и невероятно практичная ткань (100% нейлон) расширяет границы использования кресла Студент.</p>
      <h4 class="price">Цена: <span><%= @product.price %> руб.</span></h4>
      <h5 class="colors">Наличие:
          <!--Если есть-->
          <span class = "fa fa-check"></span>
          <!--Если нет-->
          <!--<span class = "fa fa-times"></span>-->
      </h5>
        <br>
      <div class="action">
        <%= button_to 'Добавить в корзину', line_items_path(product_id: @product), remote: true , class:'btn btn-danger', style:'min-width:200px' %>
      </div>
    </div>
      </div>
      <br>    
        <div class="col-md-12 product-info">
          <ul id="myTab" class="nav nav-tabs nav_tabs">

              <li class="active"><a href="#service-one" data-toggle="tab">Описание товара</a></li>
              <li><a href="#service-two" data-toggle="tab">Отзывы</a></li>
              <li><a href="#service-three" data-toggle="tab">Комментарии</a></li>

          </ul>
      <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade in active" id="service-one">
        <section class="container product-info">
          <p class = "text-g18"><%= @product.description %></p>
          <br>
          <table style = "max-width:600px;">
              <tr>
                  <td class = "info-table-left">Размер</td>
                  <td class = "info-table-left">100x100 cм.</td>
              </tr>
              <tr>
                  <td class = "info-table-left">Нагрузка max</td>
                  <td class = "info-table-left">120 кг.</td>
              </tr>
              <tr>
                  <td class = "info-table-left">Вес</td>
                  <td class = "info-table-left">3,5 кг.</td>
              </tr>
              <tr>
                  <td class = "info-table-left">Внутренний чехол</td>
                  <td class = "info-table-left">Клапан защитный</td>
              </tr>
              <tr>
                  <td class = "info-table-left">Внешний чехол</td>
                  <td class = "info-table-left">Нейлон 100%</td>
              </tr>
              <tr>
                  <td class = "info-table-left">Наполнитель</td>
                  <td class = "info-table-left">Полистерол</td>
              </tr>
          </table>
        </section>  
      </div>
    <div class="tab-pane fade" id="service-two">
      
      <section class="col-lg-7 col-md-7 col-sm-8 col-xs-12">
        <table style = "margin-top:15px;">
          <tr>
            <td class = "text-g16 review-name">Ирина Сергеева</td>
            <td class = "text-g16 review-date">28.05.2017</td>
          </tr>
          <tr>
            <td colspan = "2" class = "text-g14 review-stars-left">
              <i class = "fa fa-star text-g14"></i>
              <i class = "fa fa-star text-g14"></i>
              <i class = "fa fa-star text-g14"></i>
              <i class = "fa fa-star text-g14"></i>
              <i class = "fa fa-star text-g14 non-checked"></i>
            </td>
          </tr>
          <tr>
            <td colspan = "2" class = "text-g16 review-content">Спасибо за замечательное кресло! Не совсем то, что ожидалось, но детям очень понравилось!</td>
          </tr>
        </table>
        <p class = "text-g18">Оставить отзыв:</p>
        <textarea class="form-control" rows="3"></textarea>
        <br>
        <p class = "text-g18">Ваша оценка:</p>
        <i class = "fa fa-star text-sg14"></i><i class = "fa fa-star text-sg14"></i><i class = "fa fa-star text-sg14"></i><i class = "fa fa-star text-sg14"></i><i class = "fa fa-star text-sg14"></i>
        <br>
        <br>
        <button type = "button" class = "btn btn-danger btn-block">Оставить отзыв</button>
        <br>
      </section>
      
    </div>
    <div class="tab-pane fade" id="service-three">
                  
    </div>
  </div>
      </div>
  </div>
</item>


<% if current_user && current_user.admin? %>
  <%= link_to 'Редакторивать', edit_product_path(@product) %>
<% end %>