config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home' 
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'catalog' => 'store#index'
  get 'orders' => 'orders#index'
  get 'products' => 'products#index'
  get 'password_resets/new'
  get 'password_resets/edit'

  get 'auth/vkontakte/callback' => 'omniauth#create'
  
  resources :products
  resources :carts
  resources :line_items
  resources :orders

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/views/layouts/_benefits.html.erb
<benefits>
    <div class = "container">
        <div class = "row benefits-container">
            <div class = "col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <table>
                    <tr>
                        <td>
                            <span class="fa-stack fa-3x">
                                <i class="fa fa-circle fa-stack-2x text-l"></i>
                                <i class="fa fa-calendar fa-stack-1x fa-inverse"></i>
                            </span>
                        </td>
                        <td class = "text-g16">Работаем без выходных!</td>
                    </tr>
                </table>
            </div>
            <div class = "col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <table>
                    <tr>
                        <td>
                            <span class="fa-stack fa-3x">
                                <i class="fa fa-circle fa-stack-2x text-l"></i>
                                <i class="fa fa-refresh fa-stack-1x fa-inverse"></i>
                            </span>
                        </td>
                        <td class = "text-g16">60 дней на обмен или возврат!</td>
                    </tr>
                </table>
            </div>
            <div class = "col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <table>
                    <tr>
                        <td>
                            <span class="fa-stack fa-3x">
                                <i class="fa fa-circle fa-stack-2x text-l"></i>
                                <i class="fa fa-truck fa-stack-1x fa-inverse"></i>
                            </span>
                        </td>
                        <td class = "text-g16">Бесплатная доставка по Братску!</td>
                    </tr>
                </table>
            </div>
            <div class = "col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <table>
                    <tr>
                        <td>
                            <span class="fa-stack fa-3x">
                                <i class="fa fa-circle fa-stack-2x text-l"></i>
                                <i class="fa fa-money fa-stack-1x fa-inverse"></i>
                            </span>
                        </td>
                        <td class = "text-g16">Оплата при получении!</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</benefits>

app/views/layouts/_footer.html.erb
<div id="footer">
    <div class = "container">
        <div class = "row">
            <div class = "col-lg-4 col-md-4 col-sm-4 center-content">
                <p class = "text-w16">ИНФОРМАЦИЯ</p>
                <br>
                <a href="#"><p class = "text-w16">Контакты</p></a>
                <a href="#"><p class = "text-w16">Доставка и Оплата</p></a>

                <a href="#"><p class = "text-w16">Сотрудничество</p></a>
                <a href="#"><p class = "text-w16">О компании</p></a>
                <br>
            </div>
            <div class = "col-lg-4 col-md-4 col-sm-4 center-content">
                <p class = "text-w16">ПОКУПАТЕЛЯМ</p>
                <br>
                <a href="#"><p class = "text-w16">Каталог</p></a>
                <a href="#"><p class = "text-w16">Как выбрать кресло</p></a>
                <a href="#"><p class = "text-w16">Качество</p></a>
                <a href="#"><p class = "text-w16">Возврат и Гарантия</p></a>
                <br>
            </div>
            <div class = "col-lg-2 col-md-2 col-sm-3 col-xs-4 offset-lg-1 offset-md-1">
                <p class = "text-w16">СЛЕДИ ЗА НАМИ</p>
                <div class = "row">
                    <div class = "col-lg-3 col-md-3 col-sm-3 col-xs-3 center-content">
                        <a href = "#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-square fa-inverse fa-stack-2x"></i>
                                <i class="fa fa-vk fa-stack-1x tetx-g"></i>
                            </span>
                        </a>
                    </div>
                    <div class = "col-lg-3 col-md-3 col-sm-3 col-xs-3 center-content">
                        <a href = "#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-square fa-inverse fa-stack-2x"></i>
                                <i class="fa fa-instagram fa-stack-1x tetx-g"></i>
                            </span>
                        </a>
                    </div>
                    <div class = "col-lg-3 col-md-3 col-sm-3 col-xs-3 center-content">
                        <a href = "#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-square fa-inverse fa-stack-2x"></i>
                                <i class="fa fa-facebook fa-stack-1x tetx-g"></i>
                            </span>
                        </a>
                    </div>
                    <div class = "col-lg-3 col-md-3 col-sm-3 col-xs-3 center-content">
                        <a href = "#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-square fa-inverse fa-stack-2x"></i>
                                <i class="fa fa-odnoklassniki fa-stack-1x tetx-g"></i>
                            </span>
                        </a>
                    </div>
                </div>
                <br>
                <!--<p class = "text-w16">СПОСОБЫ ОПЛАТЫ</p>
                <p class = "text-w16">Visa/MasterCard</p>
                <img src="/assets/sberbank_small.png" class = "sberbank responsive-image">-->
            </div>
        </div>
        <p class = "text-w16">© 2003–2017 tamm'antimebel®</p>
    </div>
</div>

app/views/layouts/_header.html.erb
<header>
    <div class = "container">
        <div class = "row head-container">
            <div class = "col-lg-4 col-md-4">
              <div class = "img-responsive center-content logo">
              <%= link_to image_tag("logo.png", alt: "Tamm logo"), root_path %>
              </div>
            </div>
            <div class = "col-lg-4 col-md-4">
                <h1 class = "text-phone center-content">8 (952) 621 78 86</h1>
                <div class = "row center-content">
                    <div class="col-sm-3 hidden-lg hidden-md"></div>
                    <div class = "col-lg-6 col-md-6 col-sm-3">
                        <a href = "#" class = "btn btn-sky btn-head">ЗАКАЗАТЬ ЗВОНОК</a>
                    </div>
                    <div class = "col-lg-6 col-md-6 col-sm-3">
                        <a href = "#" class = "btn btn-sky btn-head" style = "margin-bottom:10px;">НАПИСАТЬ НАМ</a>
                    </div>
                    <div class="col-sm-3 hidden-lg hidden-md"></div>
                </div>
            </div>
            <div class = "col-lg-4 col-md-4">
                <div class = "container bag-container img-responsive">
                    <a href = <%= cart_path(@cart) %>>
                    <table class= "bag-table">
                        <tr>
                            <th rowspan="3" class = "bag-table-icon"><i class="fa fa-shopping-cart fa-2x text-g"></i></th>
                            <th class = "text-g14 bag-table-th">КОРЗИНА</th>
                        </tr>
                        <tr>
                            <td class = "text-g14 bag-table-td">Товаров:</td>                                        
                                <% if @cart %>
                                    <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>                   
                                        <td class = "text-g14 bag-table-td"><%= (@cart.total_items) %></td>
                                    <% end %>                                       
                                <% end %>
                            </td>
                        </tr>
                        <tr>
                            <td class = "text-g14 bag-table-td">На сумму:</td>                                       
                                <% if @cart %>
                                    <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
                                        <td class = "text-g14 bag-table-td"><%= number_to_currency(@cart.total_price) %></td>
                                    <% end %>                                                                    
                                <% end %>       
                            </td>                                            
                        </tr>
                    </table>
                    </a>
                </div>
            </div>
        </div>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/_slider.html.erb
<slider>
    <div id="carousel" class = "carousel slide">
        <!-- Индикаторы слайдов -->
        <ol class="carousel-indicators">
            <li class="active" data-target="#carousel" data-slide-to="0"></li>
            <li data-target="#carousel" data-slide-to="1" ></li>
            <li data-target="#carousel" data-slide-to="2" ></li>
        </ol>
        <!-- Слайды -->
        <div class="carousel-inner">
            <div class="item active">
                <img src="/assets/slide_0.png" alt="">
            </div>
            <div class="item">
                <img src="/assets/slide_1.png" alt="">
            </div>
            <div class="item">
                <img src="/assets/slide_2.png" alt="">
            </div>
        </div>
        <!-- Стрелки переключения слайдов-->
        <a href="#carousel" class="left carousel-control" data-slide="prev">
            <span class="fa fa-chevron-left fa-2x"></span>
        </a>
        <a href="#carousel" class="right carousel-control" data-slide="next">
            <span class="fa fa-chevron-right fa-2x"></span>
        </a>
    </div>    
</slider>

app/views/layouts/_subtitle.html.erb
<navbar>
    <div class = "container-fluid">
        <div class = "row">
            <nav class = "navbar navbar-sky">
                <div class = "container">
                    <div class = "navbar-header">
                        <button type = "button" class = "navbar-toggle" data-toggle="collapse" data-target="#responsive-menu">
                            <span class = "sr-only">Открыть навигацию</span>
                            <span class = "icon-bar"></span>
                            <span class = "icon-bar"></span>
                            <span class = "icon-bar"></span>
                        </button>
                    </div>
                    <div class = "collapse navbar-collapse" id = "responsive-menu">
                        <ul class = "nav navbar-nav">
                            <li><%= link_to "Главная", root_path %></li>
                            <li><%= link_to "Каталог", catalog_path %></li>
                            <li><a href="#">Доставка и оплата</a></li>
                            <li><a href="#">Как получить скидку?</a></li>
                            <li><%= link_to "Контакты", contact_path %></li>
                        </ul>
                        <nav>
                            <ul class="nav navbar-nav navbar-right">
                                <% if current_user && current_user.admin? %>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            <span class = "fa fa-edit"></span> Администрироание<b class="caret"></b>
                                        </a>
                                        <ul class="dropdown-menu">  
                                            <li><%= link_to "Пользователи", users_path %></li>
                                            <li><%= link_to "Заказы", orders_path %></li>
                                            <li><%= link_to "Товары", products_path %></li>
                                        </ul>
                                    </li>
                                <% end %>
                                <% if logged_in? %>                                   
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                           <span class = "fa fa-user"></span> Профиль <b class="caret"></b>
                                        </a>
                                        <ul class="dropdown-menu">  
                                            <li><%= link_to "Личный кабинет", current_user %></li>
                                            <li><%= link_to "Настройки", edit_user_path(current_user) %></li>
                                            <li class="divider"></li>
                                            <li>
                                                <%= link_to "Выйти", logout_path, method: "delete" %>
                                            </li>
                                        </ul>
                                    </li>
                                <% else %>
                                    <li><%= link_to "Войти", login_path %></li>
                                <% end %>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
</navbar>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>   
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag 'style' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <div id="wrap">
        <%= render 'layouts/header' %>
        <%= render 'layouts/subtitle' %>
        <%= yield %>
        <div id="push"></div>
      </div>
      <%= render 'layouts/footer' %>
  </body>
</html>